# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

max_data_cols <- function(data) {
    .Call(`_lsirmML_max_data_cols`, data)
}

make_band_matrix <- function(K) {
    .Call(`_lsirmML_make_band_matrix`, K)
}

P_lsirm_cpp <- function(theta, param) {
    .Call(`_lsirmML_P_lsirm_cpp`, theta, param)
}

llik_cpp <- function(data, grid, slope, threshold, coord, c) {
    .Call(`_lsirmML_llik_cpp`, data, grid, slope, threshold, coord, c)
}

Estep_cpp <- function(data, item, coord, grid, prior) {
    .Call(`_lsirmML_Estep_cpp`, data, item, coord, grid, prior)
}

L1L2_lsirm_cpp0 <- function(e_response, par, grid) {
    .Call(`_lsirmML_L1L2_lsirm_cpp0`, e_response, par, grid)
}

L1L2_lsirm_cpp <- function(e_response, item, coord, grid, c) {
    .Call(`_lsirmML_L1L2_lsirm_cpp`, e_response, item, coord, grid, c)
}

