# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

P_lsirm_cpp <- function(theta, param) {
    .Call(`_lsirmML_P_lsirm_cpp`, theta, param)
}

llik_cpp <- function(data, grid, item) {
    .Call(`_lsirmML_llik_cpp`, data, grid, item)
}

Estep_cpp <- function(data, item, grid, prior) {
    .Call(`_lsirmML_Estep_cpp`, data, item, grid, prior)
}

L1L2_lsirm_cpp <- function(e_response, par, grid) {
    .Call(`_lsirmML_L1L2_lsirm_cpp`, e_response, par, grid)
}

